from sqlalchemy.orm import sessionmaker
from models import *

Session = sessionmaker()
Session.configure(bind=engine)
session = Session()

if __name__ == '__main__':

    user1 = User(username='Ivan Banana', password='qwe123QWE', firstName='Alex', lastName='Xes', email='pepe@gmail.com', phone='+380665673865', userRole='moderator')
    user2 = User(username='Dudos', password=';jgs62', firstName='Oleks', lastName='Gachi', email='dudos@gmail.com', phone='+380567654340', userRole='regular')
    session.add(user1)
    session.add(user2)
    session.flush()

    category1 = Category(name='Travel')
    category2 = Category(name='Fashion')
    category3 = Category(name='Food')
    category4 = Category(name='Lifestyle')
    category5 = Category(name='Music')
    session.add(category1)
    session.add(category2)
    session.add(category3)
    session.add(category4)
    session.add(category5)
    session.flush()

    tag1 = Tag(name='eating')
    tag2 = Tag(name='beautiful place')
    tag3 = Tag(name='boots')
    tag4 = Tag(name='blogs for lifestyle')
    tag5 = Tag(name='FOOD')
    tag6 = Tag(name='Scenery')
    tag7 = Tag(name='How I like to drink!')
    session.add(tag1)
    session.add(tag2)
    session.add(tag3)
    session.add(tag4)
    session.add(tag5)
    session.add(tag6)
    session.add(tag7)
    session.flush()

    blog1 = Blog(author=user2.username,category_id=category1.id, title='THE BEST WALKING TOURS IN NEW ORLEANS', contents='New Orleans is dedicated to fun. Or, as they like to say here: laissez les bons temps rouler (let the good times roll)!')
    blog2 = Blog(author=user2.username, category_id=category2.id, title='THE MOST BEAUTIFUL BOOTS', contents='I have been on the hunt for the perfect tall lug boots this season and let me tell you guys, it was worth')
    blog3 = Blog(author=user2.username, category_id=category3.id, title='Honeynut Squash', contents='Do you like butternut squash but sometimes think it’s a bit too big? If so, super sweet and personal-sized honeynut squash is here to save the day!')
    blog4 = Blog(author=user2.username, category_id=category4.id, title='27 Best Lifestyle Blogs to Follow in 2021', contents='The Lifestyle Blog niche is one of the most competitive blogging niches around. Lifestyle bloggers are competing against digital lifestyle magazines, in a niche that is already quite saturated.')
    session.add(blog1)
    session.add(blog2)
    session.add(blog3)
    session.add(blog4)
    session.flush()

    # blog1.tags.append(tag2)
    # blog1.tags.append(tag6)
    # blog2.tags.append(tag3)
    # blog3.tags.append(tag1)
    # blog3.tags.append(tag5)
    # blog3.tags.append(tag7)
    # blog4.tags.append(tag4)
    # session.flush()

    editedBlog1 = EditedBlog(originalBlog_id=blog1.id)
    editedBlog2 = EditedBlog(originalBlog_id=blog2.id, title='the most beautiful boots')
    editedBlog3 = EditedBlog(originalBlog_id=blog3.id, contents='Top 5 the recipes for cooking Honeynut Squash:')
    editedBlog4 = EditedBlog(originalBlog_id=blog4.id)
    session.add(editedBlog1)
    session.add(editedBlog2)
    session.add(editedBlog3)
    session.add(editedBlog4)
    session.flush()

    session.commit()